export const SKILLS: string[] = [
  "React.js",
  "Next.js",
  "TypeScrpt",
  "Node.js",
  "JavaScript",
  "Git",
  "GitHub",
  "Express",
  "MongoDB",
  "MySQL",
  "PostgreSQL",
  "Prisma",
  "Mongoose",
  "REST API",
  "Vercel",
  "Docker",
  "Redux",
  "Redux Saga",
  "ShadCN UI",
  "Tailwind CSS",
  "Prime React",
  "NX Monorepo",
  "Microservices",
  "Bitbucket",
  "TurboRepo",
  "Ant Design",
  "Prime React",
  "Docker",
  "NX Monorepo",
  "Microservices",
];
